# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49824e8b193aec24a9519acbaf2db7dcd77e9783b62f673a403c28ab9e427897efc389e8a7d8727b4129104a5faca656ea78ef83b0d88e242c0e7acb2560aa1f

test:
  secret_key_base: d34d115363237ee0113a1e5de61adc14be7e6775f997a54f3c5ded32483d27dfd4f9c27c69f66b274eabea9eee52de1c0381fe7e15a8784d68c3ff4fc309385d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
